Dev Branch
Vestels/chat pull request #1
Opened 2024-12-12 09:49 UTC by Vestels

Implemented property validations on Create / Delete methods and AuthGuard for Update / Delete for only own datas.

2024-12-13 06:59 UTC, Psychol0g1st requested changes

2024-12-13 06:59 UTC, Psychol0g1st commented on backend/src/users/users.service.ts
> +    if (existingUser._id.toString() !== currentUserId) {
Most képzeld el azt, hogy sok végpontnál meg kell csinálni azt, hogy csak a sajátját tudja módosítani. Mindenhova be fogod másolni ezt a kódod? És ha bővíteni kell, akkor mindegyilknél egyesével kell végigmenni. Nagyon nem hatékony és CLEAN CODE és SOLID elveket nem tartod be ezáltal. Ezt ki lehet szervezni, méghozzá NestJs-nek erre vannak eszközök. Pl a guardok. Hasonlóan csinálod a JWT autentikációt is. Na , csak saját adat módosítást is ugyan így meg lehet csinálni, nézz utána jobban a **Guard**-oknak. És ezt refaktoráld.

2024-12-13 06:59 UTC, Psychol0g1st commented on backend/src/users/users.service.ts
> +    if (existingUser._id.toString() !== currentUserId) {
És itt is ugyan az a kód, ami ellenőrzi, hogy saját adatait módosítja.

2024-12-13 10:14 UTC, Vestels commented on backend/src/users/users.service.ts
> +    if (existingUser._id.toString() !== currentUserId) {
Csináltam egy OwnershipGuardot ezekhez, illetve egy helpert a userekhez hogy amit lehet még ki legyen szervezve.

2024-12-13 10:14 UTC, Vestels commented on backend/src/users/users.service.ts
> +    if (existingUser._id.toString() !== currentUserId) {
Javítottam ezt is.

2024-12-16 08:07 UTC, Psychol0g1st reviewed
Az environment fájlt még próbáld megoldani és jó lesz

2024-12-16 08:07 UTC, Psychol0g1st commented on backend/src/main.ts
>    const PORT = DbConfig.port || 5000;
Az environment fájlokkal mi volt a gond? Azzal kellene megoldani.

2024-12-16 08:07 UTC, Psychol0g1st commented on backend/src/users/users.service.ts
Na ugye mennyivel tisztább a kód? :D

2024-12-16 08:11 UTC, Vestels commented on backend/src/main.ts
>    const PORT = DbConfig.port || 5000;
ez a cors options, másképpen frontendről a hívásokat letiltja

2024-12-16 08:21 UTC, Psychol0g1st commented on backend/src/main.ts
>    const PORT = DbConfig.port || 5000;
Az rendben van. A PORT-ra vonatkozott a komment.

2024-12-16 08:41 UTC, Psychol0g1st approved these changes
Oké

2024-12-16 08:41 UTC, merged